export const copy = {
  title: "AI Academic Audit",
  subtitle: "Analisis Pola Penulisan Akademik",
  tagline:
    "Unggah PDF akademik berbahasa Indonesia untuk melihat indikator probabilistik pola tulisan. Bukan deteksi pasti AI vs manusia.",
  disclaimerTitle: "Interpretasi Hasil",
  disclaimerBody:
    "Analisis ini bersifat probabilistik dan dirancang sebagai alat bantu evaluasi pola penulisan akademik. Hasil tidak dapat digunakan sebagai penentu pasti apakah suatu teks ditulis oleh AI maupun manusia.",
  uploadTitle: "Unggah Dokumen PDF",
  uploadHint: "Seret dan lepas file PDF, atau klik untuk memilih",
  uploadLimit: "Maks. 12 MB · PDF · Bahasa Indonesia",
  optionsTitle: "Pengecualian analisis (opsional)",
  optionsHint:
    "Centang bagian yang ingin dikecualikan dari perhitungan skor. Tidak ada pengecualian otomatis tanpa pilihan Anda.",
  excludeToc: "Kecualikan daftar isi",
  excludeBibliography: "Kecualikan daftar pustaka",
  excludeAppendix: "Kecualikan lampiran",
  excludeCaptions: "Kecualikan judul tabel & caption",
  excludePagesLabel: "Halaman yang tidak ingin dianalisis",
  excludePagesHint: "Contoh: 1,2,5,10-15 (kosongkan jika tidak ada)",
  processing: "Analisis sedang berjalan",
  processingHint:
    "Mengekstrak teks, menganalisis pola tulisan, dan menyusun laporan PDF…",
  summaryTitle: "Ringkasan Analisis",
  pageCount: "Halaman dokumen",
  avgScore: "Rata-rata skor pola",
  kuat: "Pola kuat",
  sedang: "Pola sedang",
  ringan: "Pola ringan",
  natural: "Cenderung natural",
  excludedTitle: "Bagian dikecualikan",
  interpretation: "Ringkasan interpretasi",
  paragraphs: "Detail per paragraf",
  download: "Unduh Laporan PDF",
  newDoc: "Analisis dokumen baru",
  scoreLabel: "Indikator probabilistik pola tulisan",
  truncated:
    "Dokumen dipotong: hanya sebagian paragraf awal yang dianalisis (batas layanan).",
  errorGeneric: "Terjadi kesalahan. Silakan coba lagi.",
  backHub: "Kembali ke Agisna Dev",
} as const;
