/** Common English typing words (~320). */
export const ENGLISH_WORDS: readonly string[] = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "find", "here", "thing", "many", "tell", "very", "still", "through", "life", "world",
  "feel", "great", "before", "move", "right", "boy", "old", "too", "same", "another",
  "line", "must", "start", "might", "end", "put", "home", "hand", "large", "spell",
  "air", "where", "help", "small", "every", "found", "study", "learn", "plant", "cover",
  "food", "sun", "four", "thought", "let", "keep", "eye", "never", "last", "door",
  "between", "city", "tree", "cross", "since", "hard", "begin", "seem", "together", "follow",
  "came", "show", "local", "believe", "hold", "bring", "happen", "write", "provide", "run",
  "grow", "open", "walk", "win", "offer", "remember", "love", "wait", "serve", "appear",
  "build", "stay", "fall", "oh", "pass", "lead", "understand", "watch", "stand", "own",
  "create", "design", "code", "ship", "focus", "flow", "keyboard", "typing", "speed",
  "accuracy", "practice", "premium", "glass", "purple", "violet", "creator", "developer",
  "interface", "motion", "smooth", "digital", "cloud", "server", "client", "network",
  "secure", "modern", "clean", "simple", "elegant", "rapid", "quiet", "bright", "clear",
  "strong", "quick", "calm", "bold", "fresh", "sharp", "warm", "cool", "light", "dark",
  "water", "earth", "fire", "wind", "rain", "snow", "river", "ocean", "mountain", "forest",
  "music", "sound", "rhythm", "color", "shape", "space", "energy", "power", "mind", "heart",
  "dream", "hope", "truth", "peace", "joy", "trust", "faith", "grace", "honor", "pride",
  "skill", "craft", "trade", "market", "value", "price", "brand", "story", "voice", "team",
  "goal", "plan", "task", "step", "path", "route", "map", "guide", "hint", "clue",
  "game", "play", "score", "level", "round", "match", "race", "track", "field", "court",
  "book", "page", "word", "letter", "note", "list", "form", "table", "chart", "graph",
  "pixel", "frame", "layer", "block", "grid", "node", "link", "port", "cache", "queue",
  "stack", "array", "object", "class", "method", "function", "variable", "string", "number",
  "boolean", "async", "await", "promise", "module", "export", "import", "return", "break",
];
