/** Indonesian typing words (~160). */
export const INDONESIAN_WORDS: readonly string[] = [
  "yang", "dan", "di", "dari", "ini", "itu", "dengan", "untuk", "adalah", "pada",
  "akan", "tidak", "saya", "kamu", "kita", "mereka", "bisa", "sudah", "masih", "juga",
  "atau", "jika", "karena", "saat", "telah", "ada", "oleh", "ke", "dalam", "sebagai",
  "lebih", "sangat", "hanya", "semua", "setiap", "banyak", "beberapa", "orang", "waktu",
  "tahun", "hari", "bulan", "malam", "pagi", "siang", "rumah", "kota", "negara", "dunia",
  "air", "makanan", "minum", "kerja", "sekolah", "belajar", "mengajar", "baca", "tulis",
  "kata", "kalimat", "bahasa", "indonesia", "inggris", "teknologi", "komputer", "internet",
  "website", "aplikasi", "program", "sistem", "data", "informasi", "digital", "online",
  "kreatif", "desain", "warna", "gambar", "video", "musik", "suara", "cerita", "film",
  "teman", "keluarga", "anak", "ibu", "ayah", "kakak", "adik", "tetangga", "guru", "murid",
  "jalan", "jalanan", "mobil", "motor", "bus", "kereta", "pesawat", "kapal", "bandara",
  "pasar", "toko", "harga", "uang", "beli", "jual", "murah", "mahal", "gratis", "promo",
  "sehat", "sakit", "dokter", "obat", "rumah", "sakit", "olahraga", "lari", "berjalan", "istirahat",
  "senang", "sedih", "marah", "takut", "cinta", "sayang", "bahagia", "tenang", "sabar", "berani",
  "cepat", "lambat", "besar", "kecil", "tinggi", "rendah", "panjang", "pendek", "baru", "lama",
  "mengetik", "latihan", "kecepatan", "akurasi", "keyboard", "huruf", "angka", "simbol", "spasi",
  "fokus", "disiplin", "target", "tujuan", "rencana", "proses", "hasil", "sukses", "gagal", "coba",
  "buka", "tutup", "mulai", "selesai", "lanjut", "ulang", "hapus", "simpan", "kirim", "terima",
  "lihat", "dengar", "rasa", "pikir", "tahu", "ingat", "lupa", "cari", "temukan", "pilih",
  "buat", "ubah", "hapus", "pasang", "lepas", "masuk", "keluar", "naik", "turun", "datang",
  "pergi", "tinggal", "tinggalkan", "tunggu", "bantu", "tolong", "terima", "kasih", "maaf", "permisi",
];
