export const QUOTES: readonly string[] = [
  "The only way to do great work is to love what you do.",
  "Simplicity is the ultimate sophistication.",
  "Code is like humor. When you have to explain it, it is bad.",
  "First, solve the problem. Then, write the code.",
  "Design is not just what it looks like. Design is how it works.",
  "The future depends on what you do today.",
  "Focus on being productive instead of busy.",
  "Small steps every day lead to big results.",
  "Quality is not an act, it is a habit.",
  "Make it work, make it right, make it fast.",
  "Programs must be written for people to read.",
  "Any fool can write code that a computer can understand.",
  "The best error message is the one that never shows up.",
  "Talk is cheap. Show me the code.",
  "Perfection is achieved not when there is nothing more to add.",
  "It does not matter how slowly you go as long as you do not stop.",
  "We are what we repeatedly do. Excellence is a habit.",
  "The secret of getting ahead is getting started.",
  "Do not watch the clock; do what it does. Keep going.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Typing speed is a skill built one keystroke at a time.",
  "Consistency beats intensity when you are building mastery.",
  "Clear thinking becomes clear writing on the keyboard.",
  "Practice with intention and your fingers will follow.",
];
